services:
    admin-node:
        build:
            context: ./docker
            dockerfile: ./node/node.Dockerfile
        ports:
            - ${HOST_ADMIN_PORT:-5173}:5173
        command: sh -c "npm install && npm run dev"
        volumes:
            - ./admin:/home/node
        environment:
            BASE_ADMIN_URL: ${BASE_ADMIN_URL}
            BASE_BACKEND_URL: ${BASE_BACKEND_URL}
        user: ${DOCKER_USER:-1000:1000}
